[package]
name = "git_repos"
version = "0.1.5"
edition = "2021"
publish = false
description = "Native zshrs plugin porting zsh-git-repo-cache (gitrepos)"
authors = ["MenkeTechnologies"]
repository = "https://github.com/MenkeTechnologies/zshrs-git-repos"
homepage = "https://github.com/MenkeTechnologies/zshrs-git-repos"

[lib]
name = "git_repos"
crate-type = ["cdylib", "rlib"]

[dependencies]
znative = "0.12"
